name: CI

on:
  pull_request_target:
    types: [labeled, synchronize, unlocked, opened]

jobs:
  setup_qa1_branch:
    if: contains(github.event.pull_request.labels.*.name, 'qa-1')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}          

      - name: Create branch and force push
        run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            git checkout -b internal/qa-1/PR-${{ github.event.number }}/$GITHUB_HEAD_REF
            git push -f --set-upstream origin internal/qa-1/PR-${{ github.event.number }}/$GITHUB_HEAD_REF
