name: CI

on:
  pull_request_target:
    types: [labeled, synchronize, unlocked, opened]

jobs:
  setup_qa1_branch:
    if: contains(github.event.pull_request.labels.*.name, 'qa-1')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
          path: main
          
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}    
          path: pr

      - name: Create branch
        run: |
            cd main
            git config user.name github-actions
            git config user.email github-actions@github.com
            git checkout -b internal/qa-1/PR-${{ github.event.number }}/$GITHUB_HEAD_REF
            cd ..

      - name: Sync select files
        run: |
            rsync -avz --delete --no-perms --no-owner --no-group --exclude=.github --exclude=.gitlab-ci.yml rp/ main

      - name: Push branch
        run: |
            cd main
            git add .
            git commit -m "Created QA branch from PR ${{ github.event.number }}"
            git push -f --set-upstream origin internal/qa-1/PR-${{ github.event.number }}/$GITHUB_HEAD_REF
